extends:
  - stylelint-config-standard
  - stylelint-config-idiomatic-order
rules:
  at-rule-empty-line-before: null
  indentation: 4
  at-rule-no-unknown:
    - true
    - ignoreAtRules:
        - if
        - else
        - each
        - for
        - while
        - function
        - return
        - include
        - mixin
        - extend
        - content
        - at-root
        - error
  no-descending-specificity: null
  selector-type-no-unknown:
    - true
    - ignoreTypes:
        - "_"
        - x
  no-duplicate-selectors: true
  selector-pseudo-class-no-unknown: true
  shorthand-property-no-redundant-values: true
  selector-list-comma-newline-after: always
  value-keyword-case: lower
  selector-type-case: lower
  unit-case: lower
  unit-no-unknown: true
  media-feature-parentheses-space-inside: never
  selector-descendant-combinator-no-non-space: true
  function-calc-no-invalid: null
