version: "3.3"

services:
  backend:
    build:
      context: ./backend
      dockerfile: dockerfiles/dev/Dockerfile
    environment:
      SECRET_KEY:
    env_file:
      - .env_dev
    volumes:
      - ./backend:/home/backend

  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfiles/dev/Dockerfile
    ports:
      - "80:8080"
    volumes:
      - ./frontend:/home/frontend
    tty: true

  db:
    image: postgres:12
    env_file:
      - .env_dev
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
