version: "3.3"

services:
  backend:
    depends_on:
      - db
    networks:
      - backend
      - frontend

  frontend:
    networks:
      - frontend

  db:
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: matcha
    networks:
      - backend
    restart: always

networks:
  backend:
  frontend:
