version: "3.3"

services:
  backend:
    depends_on:
      - db
    networks:
      - backend
      - frontend

  frontend:
    networks:
      - frontend

  db:
    networks:
      - backend
    restart: always

networks:
  backend:
  frontend:
