version: "3.8"

services:
  backend:
    networks:
      - backend
      - frontend
    depends_on:
      - db

  frontend:
    networks:
      - frontend
    ports:
      - "3000:3000"
    tty: true

  db:
    networks:
      - backend
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: matcha
    restart: always

networks:
  backend:
  frontend:
